/* Auto-generated by train.py. Do not edit. */
#ifndef MINIGPT_DATA_H
#define MINIGPT_DATA_H

#define N_LAYER     1
#define N_EMBD      16
#define BLOCK_SIZE  16
#define N_HEAD      4
#define HEAD_DIM    (N_EMBD / N_HEAD)
#define VOCAB_SIZE  27
#define BOS_TOKEN   26

extern const char uchars[VOCAB_SIZE];

extern const float wte[VOCAB_SIZE][N_EMBD];
extern const float wpe[BLOCK_SIZE][N_EMBD];
extern const float lm_head[VOCAB_SIZE][N_EMBD];
extern const float attn_wq[N_LAYER][N_EMBD][N_EMBD];
extern const float attn_wk[N_LAYER][N_EMBD][N_EMBD];
extern const float attn_wv[N_LAYER][N_EMBD][N_EMBD];
extern const float attn_wo[N_LAYER][N_EMBD][N_EMBD];
extern const float mlp_fc1[N_LAYER][4*N_EMBD][N_EMBD];
extern const float mlp_fc2[N_LAYER][N_EMBD][4*N_EMBD];

#endif
