/*
 * Minigpt inference - uses weights from data.c (generated by train.py).
 * Compile: gcc -O2 -o infer infer.c data.c -lm
 * Run: ./infer
 */

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <math.h>
#include <time.h>

#include "data.h"

/* -------------------------------------------------------------------------
 * RNG for sampling
 * ------------------------------------------------------------------------- */
static unsigned long long rng_state = 12345;
static double rng_uniform(void) {
    rng_state = rng_state * 6364136223846793005ULL + 1442695040888963407ULL;
    return (double)((rng_state >> 33) & 0x7FFFFFFF) / (double)0x7FFFFFFF;
}

/* -------------------------------------------------------------------------
 * Forward helpers (no autograd, plain float ops)
 * ------------------------------------------------------------------------- */

static void linear(const float *x, const float *w, int wrows, int wcols, float *out) {
    for (int i = 0; i < wrows; i++) {
        float acc = 0.0f;
        for (int j = 0; j < wcols; j++)
            acc += w[i * wcols + j] * x[j];
        out[i] = acc;
    }
}

static void softmax(const float *logits, int n, float *out) {
    float max_val = logits[0];
    for (int i = 1; i < n; i++)
        if (logits[i] > max_val) max_val = logits[i];

    float total = 0.0f;
    for (int i = 0; i < n; i++) {
        out[i] = expf(logits[i] - max_val);
        total += out[i];
    }
    for (int i = 0; i < n; i++)
        out[i] /= total;
}

static void rmsnorm(const float *x, int n, float *out) {
    float ms = 0.0f;
    for (int i = 0; i < n; i++)
        ms += x[i] * x[i];
    ms /= n;
    float scale = 1.0f / sqrtf(ms + 1e-5f);
    for (int i = 0; i < n; i++)
        out[i] = x[i] * scale;
}

/* -------------------------------------------------------------------------
 * KV cache (per layer, per position)
 * ------------------------------------------------------------------------- */
static float keys_cache[N_LAYER][BLOCK_SIZE][N_EMBD];
static float vals_cache[N_LAYER][BLOCK_SIZE][N_EMBD];
static int kv_len[N_LAYER];

static void gpt_forward(int token_id, int pos_id, float *logits_out) {
    float x[N_EMBD];
    float xn[N_EMBD];

    /* token + position embedding */
    for (int i = 0; i < N_EMBD; i++)
        x[i] = wte[token_id][i] + wpe[pos_id][i];

    rmsnorm(x, N_EMBD, xn);
    memcpy(x, xn, sizeof(x));

    for (int li = 0; li < N_LAYER; li++) {
        /* --- Attention --- */
        float x_res[N_EMBD];
        memcpy(x_res, x, sizeof(x));

        rmsnorm(x, N_EMBD, xn);

        float q[N_EMBD], k[N_EMBD], v[N_EMBD];
        linear(xn, (const float *)attn_wq[li], N_EMBD, N_EMBD, q);
        linear(xn, (const float *)attn_wk[li], N_EMBD, N_EMBD, k);
        linear(xn, (const float *)attn_wv[li], N_EMBD, N_EMBD, v);

        /* store in kv cache */
        int t = kv_len[li];
        for (int i = 0; i < N_EMBD; i++) {
            keys_cache[li][t][i] = k[i];
            vals_cache[li][t][i] = v[i];
        }
        kv_len[li]++;
        int seq_len = kv_len[li];

        /* multi-head attention */
        float x_attn[N_EMBD];
        float scale = 1.0f / sqrtf((float)HEAD_DIM);
        for (int h = 0; h < N_HEAD; h++) {
            int hs = h * HEAD_DIM;
            /* attention logits */
            float attn_logits[BLOCK_SIZE];
            for (int tt = 0; tt < seq_len; tt++) {
                float dot = 0.0f;
                for (int j = 0; j < HEAD_DIM; j++)
                    dot += q[hs + j] * keys_cache[li][tt][hs + j];
                attn_logits[tt] = dot * scale;
            }
            float attn_w[BLOCK_SIZE];
            softmax(attn_logits, seq_len, attn_w);
            /* weighted sum over values */
            for (int j = 0; j < HEAD_DIM; j++) {
                float acc = 0.0f;
                for (int tt = 0; tt < seq_len; tt++)
                    acc += attn_w[tt] * vals_cache[li][tt][hs + j];
                x_attn[hs + j] = acc;
            }
        }

        float x_proj[N_EMBD];
        linear(x_attn, (const float *)attn_wo[li], N_EMBD, N_EMBD, x_proj);
        for (int i = 0; i < N_EMBD; i++)
            x[i] = x_proj[i] + x_res[i];

        /* --- MLP --- */
        memcpy(x_res, x, sizeof(x));
        rmsnorm(x, N_EMBD, xn);

        float fc1_out[4 * N_EMBD];
        linear(xn, (const float *)mlp_fc1[li], 4*N_EMBD, N_EMBD, fc1_out);
        for (int i = 0; i < 4 * N_EMBD; i++)
            fc1_out[i] = fc1_out[i] > 0.0f ? fc1_out[i] : 0.0f;

        float fc2_out[N_EMBD];
        linear(fc1_out, (const float *)mlp_fc2[li], N_EMBD, 4*N_EMBD, fc2_out);
        for (int i = 0; i < N_EMBD; i++)
            x[i] = fc2_out[i] + x_res[i];
    }

    /* lm_head */
    linear(x, (const float *)lm_head, VOCAB_SIZE, N_EMBD, logits_out);
}

/* -------------------------------------------------------------------------
 * Main
 * ------------------------------------------------------------------------- */
void infer(const char *prefix)
{
    rng_state = (unsigned long long)time(NULL);

    float temperature = 0.5f;
    printf("prefix: %s\n", prefix);
    printf("--- minigpt inference (generated names) ---\n");

    for (int sample_idx = 0; sample_idx < 20; sample_idx++) {
        memset(kv_len, 0, sizeof(kv_len));

        int token_id = BOS_TOKEN;
        char sample[64];
        int slen = 0;

        for (int pos = 0; pos < BLOCK_SIZE; pos++) {
            float logits[VOCAB_SIZE];
            gpt_forward(token_id, pos, logits);

            /* scale by temperature */
            float probs[VOCAB_SIZE];
            for (int i = 0; i < VOCAB_SIZE; i++)
                logits[i] /= temperature;
            softmax(logits, VOCAB_SIZE, probs);

            /* sample */
            float r = (float)rng_uniform();
            float cum = 0.0f;
            token_id = VOCAB_SIZE - 1;
            for (int i = 0; i < VOCAB_SIZE; i++) {
                cum += probs[i];
                if (r < cum) {
                    token_id = i;
                    break;
                }
            }
            if (token_id == BOS_TOKEN)
                break;
            if (slen < 63 && token_id < VOCAB_SIZE - 1)
                sample[slen++] = (char)uchars[token_id];
        }
        sample[slen] = '\0';
        printf("sample %2d: %s\n", sample_idx + 1, sample);
    }

}
